### ISSUE TITLE
A lot of reathentications

### ISSUE THREAD

**Issue by ErikT80** [TobiasLaross/Hass-Lynk-Co#48] opened 2024-07-01 16:44 UTC
For the last week I need to re authenticate at least every day, but sometimes even multiple times a day.

I also have the feeling I need to login to my account in the car itself. This wasn't happening before.

**Comment by TobiasLaross** [comment] 2024-07-01 18:35
I have been experiencing the same, I just increased the polling time to 240min but I don’t think that will help. Hopefully it will start working more stable soon

**Comment by robbinonline** [comment] 2024-07-02 09:26
Same issue here, i have to reconfigure every day.

**Comment by pjgrun** [comment] 2024-07-02 11:15
Same issue here. 
In addition, I observed that data update frequency was reduced in past days, and today data is taking hours to update, if at all. Debug logs do not show any strange behavior.

**Comment by pjgrun** [comment] 2024-07-02 12:40
Furthermore, I have tested that I can get updated values using official app, but integration still reports outdated data, despite logs indicating successful refresh

**Comment by pjgrun** [comment] 2024-07-02 14:54
It appears I was suffering from issue #43 . Had to remove integration completely, restart HA and reinstall integration.

**Comment by b12e** [comment] 2024-07-03 09:02
Same here. It ran smoothly for a while and then since last week it's asking to re-auth every day or sometimes multiple times a day.

**Comment by TobiasLaross** [comment] 2024-07-03 09:21
The issue is that the ccc_token is none which needs to be refreshed every day and when it fails I assumed it would not be able to recover. But last bight I decided not the re-authenticate and today it recovered, so maybe I need to update the logic to ask for re-authentication when refresh_token is None

**Comment by TobiasLaross** [comment] 2024-07-09 14:05
I have not found a solution for this, I’m trying now without any reloading/data fetching and will get back in 2 days to see if I’m able to get a new cccToken

**Comment by TobiasLaross** [comment] 2024-07-10 12:09
@Ferrox85 Great news because I was out of ideas, I have not used the official app much at all

**Comment by Ferrox85** [comment] 2024-07-10 12:19
Now, if everybody calls the servicedesk with this issue, maybe it will be resolved quicker...

**Comment by Ferrox85** [comment] 2024-07-11 11:14
I've read somewhere else that there has been a software fix for this issue. I have to wait for an few hours to confirm it is fixed.

**Comment by TobiasLaross** [comment] 2024-07-13 05:32
Works for me so far at least

**Comment by Ferrox85** [comment] 2024-07-22 08:51
It seems to be fixed for me as well... close this issue?

**Closed** 2024-07-22 09:56 UTC
