### ISSUE TITLE
Unknown error when configuring car.

### ISSUE THREAD

**Issue by MichelK1968** [TobiasLaross/Hass-Lynk-Co#39] opened 2024-06-21 22:12 UTC
When configuring the car by filling in e-mail, password en vin number an unknown error apears.

**Comment by TobiasLaross** [comment] 2024-06-22 04:43
What does the log say? Can you log in on the official app?

**Comment by MichelK1968** [comment] 2024-06-22 17:25
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 7:16:29 PM (1 occurrences)
Last logged: 7:16:29 PM 

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lynkco/config_flow.py", line 87, in async_step_user>
    ) = await login(email, password, session)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lynkco/login_flow.py", line 43, in login
    page_view_id, referer_url = await getCombinedSigninAndSignup(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lynkco/login_flow.py", line 178, in getCombinedSigninAndSignup
    async with session.get(url, params=params, headers=headers) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 672, in _request
    raise ValueError("Can redirect only to http or https")
ValueError: Can redirect only to http or https


Yes I can log in to the official app without any problems.

**Comment by TobiasLaross** [comment] 2024-06-23 13:39
Can you provide all logs that lynkco produces during the login attempt as well? 
Did you get SMS with 2-factor code?
Can you replace the file custom_components/lynkco/login_flow.py with this file and reboot HASS and try again?
https://github.com/TobiasLaross/Hass-Lynk-Co/blob/bugfix/login-getcombinedsas-unknown-error/custom_components/lynkco/login_flow.py

It wont fix the issue but maybe it will help me understand what the issue is.

**Comment by MichelK1968** [comment] 2024-06-24 05:42
I can't find specific logs from logging in to Lynk&co.  Where can I find it? I'm using the app from Homeassistant.  My Homeassistant is installed on a raspberry 4. No, 2way authenticating isn't working I don't get a code.  Tried to place the other File  but cut & paste doesn't work. Tried with different versions and even when I type a wrong password the same errror message occurs. Only with a wrong vin number i got another message. Maybe you got a tip for me?

**Comment by TobiasLaross** [comment] 2024-06-24 15:14
No I don’t know what is wrong, the best would be if you could replace the file so I can see the extra logs. You can install addon: VS Code

the logs can be found: Settings->System->Logs
Scroll down to show full logs
And filter on lynkco

**Comment by MichelK1968** [comment] 2024-06-24 20:52
I added the code you send me and I don't know why but it works fine now. My car is added to Home Assistant So I Want to thank you for your time en effort.

**Closed** 2024-06-25 14:43 UTC
