### ISSUE TITLE
Fails to fetch vehicle data

### ISSUE THREAD

**Issue by fnordpojk** [TobiasLaross/Hass-Lynk-Co#23] opened 2024-04-21 22:43 UTC
Logger: custom_components.lynkco.data_fetcher
Source: custom_components/lynkco/data_fetcher.py:48
integration: Lynk & Co ([documentation](https://www.github.com/tobiaslaross/Hass-Lynk-Co), [issues](https://github.com/tobiaslaross/Hass-Lynk-Co/issues))
First occurred: 00:40:09 (2 occurrences)
Last logged: 00:40:09

Failed to fetch vehicle data, HTTP status: 403, response: {"timestamp":"2024-04-21T22:40:09.408+00:00","status":403,"error":"Forbidden","path":"/api/v1/vds/vehicles/myvin/data/record"}
Failed to fetch vehicle data, HTTP status: 403, response: {"timestamp":"2024-04-21T22:40:09.415+00:00","status":403,"error":"Forbidden","path":"/api/v1/vds/vehicles/myvin/data/shadow"}

Perhaps Lynk has changed something in the API?

**Comment by fnordpojk** [comment] 2024-04-22 00:55
Refreshing tokens and forcing updates did nothing. Removed and re-added the integration, and after forcing an update, I now have data. Weird..

**Comment by TobiasLaross** [comment] 2024-04-22 08:28
I have seen the same logs a couple of days ago, it seems like there is some kind of rate limiting, that is why I increased the polling time. I configures my device to update every 4th hour and it seems to be working. I had those logs yesterday evening at 11pm and then no updates during the night and it works again this morning. I think my ccc token will be refreshed in the afternoon so it means that the same token that wasn't working yesterday evening is working now. 
Maybe I will need to add a cooldown period for a couple of hours after 403 error, don't know... I will keep this issue open so we can add more info here

**Comment by pjgrun** [comment] 2024-05-09 08:48
I updated yestedrday to V1.3.0 and I am now getting this kind of errors:

![image](https://github.com/TobiasLaross/Hass-Lynk-Co/assets/89712102/0c42520a-a56e-47b7-b6cb-9c093cb0ce2f)

**Comment by pjgrun** [comment] 2024-05-09 12:06
While root cause of loosing authentication can be found, it would be really helpful to be able to force user re-authentication without having to delete and re-install the integration

**Comment by TobiasLaross** [comment] 2024-05-09 18:37
@pjgrun Yes I thought I added re-authentication by `raise ConfigEntryAuthFailed` but apparently it didn’t work as expected… 
Can you give more details of the root cause, how have you configured the scan interval and how many times(how frequently) have you force refreshed the last 24h? Dis you also get 403 earlier in the logs? 

When you re-added the integration did it start working as expected immediately?

**Comment by pjgrun** [comment] 2024-05-10 07:32
I started using your integration May 1st and from beginning I set the scan interval to 60 minutes (despite your comments regarding throttling). I did not observe any 403 issues during my testing until the disconnection yesterday.
In Lynk&Co user forums I read that yesterday many users had issues with the official app, were automatically logged out, and then had difficulties to log in again. In my case, with the integration, everything went Ok once I re-installed integration and re-authenticated. Just took a few attempts to authenticate due to delays in receiving the 2FA code from Link&Co. 
When I reinstalled integration, I forgot to activate debug logs, so I have no recent log information after installation. I have enabled them now, and will provide any updates when available.
`raise ConfigEntryAuthFailed` -> How would that work? Would it prompt in HA UI to re-enter credentials and 2FA code?

**Comment by TobiasLaross** [comment] 2024-05-10 16:49
Yes it would promt user to re-auth but I had misunderstood how it worked, i also need to call async_step_reauth, I will implement a fix soon

**Comment by pjgrun** [comment] 2024-05-10 17:08
Please find logs from 10:00 to 19:00 today. Scan interval set to 60 minutes, all working fine

![image](https://github.com/TobiasLaross/Hass-Lynk-Co/assets/89712102/4ab3d976-57ae-4cbd-974c-fd445ec295a9)
![image](https://github.com/TobiasLaross/Hass-Lynk-Co/assets/89712102/8db93307-9911-4fa5-b8dc-a6d79c8313a2)

**Comment by TobiasLaross** [comment] 2024-05-16 09:34
@pjgrun Is it still stable for you with updates every hour?

**Comment by pjgrun** [comment] 2024-05-16 09:36
Yes, it is.

**Comment by TobiasLaross** [comment] 2024-05-19 18:08
Closing this issue since it is likely caused by Lynk instability and/or rate limiting, I created a discussion where we can continue discussing the stability instead and I will likely not be able to solve the root cause of the 403 error. 
https://github.com/TobiasLaross/Hass-Lynk-Co/discussions/31

**Closed by TobiasLaross** 2024-05-19 18:08 UTC
